<link rel='stylesheet' href='../assets/css/main.css'/>

# Multiple Logistic Regression in Python  - College Admission

### Overview
Predict college admission using Multiple Logistic Regression
 
### Builds on
None

### Run time
approx. 10-20 minutes

### Notes

In [2]:
%matplotlib inline

import numpy as np
import pandas as pd
from scipy import stats
import statsmodels.formula.api as sm
import matplotlib.pyplot as plt

## Step 1: College Admission Data

Let's look at the college admission data.  Here, we have some student test scores, GPA, and Rank, followed by whether the student was admitt ed or not.


|gre  |gpa  |rank |  admitted |
|-----------------------------|
|380  |3.61 | 3   |    no     |
|660  |3.67 | 1   |    yes    |
|800  |4.0  | 1   |    yes    |
|640  |3.19 | 4   |    yes    |
|520  |2.93 | 4   |    no     |
|760  |3.0  | 2   |    yes    |

## Step 1: Let's create a Pandas dataframe with the data

In [4]:
admissions = pd.read_csv("/data/college-admissions/admission-data.csv")
admissions.columns = ["admit", "gre", "gpa", "prestige"]

admissions

    admit  gre   gpa  prestige
0       0  380  3.61         3
1       1  660  3.67         3
2       1  800  4.00         1
3       0  640  3.19         4
4       0  520  2.93         4
5       1  760  3.00         2
6       0  560  2.98         1
7       0  400  3.08         2
8       0  540  3.39         3
9       1  700  3.92         2
10      1  800  4.00         4
11      0  440  3.22         1
12      1  760  4.00         1
13      1  700  3.08         2
14      1  700  4.00         1
15      0  480  3.44         3
16      1  780  3.87         4
17      0  360  2.56         3
18      1  800  3.75         2
19      0  540  3.81         1
20      0  500  3.17         3
21      1  660  3.63         2
22      0  600  2.82         4
23      0  680  3.19         4
24      1  760  3.35         2
25      1  800  3.66         1
26      1  620  3.61         1
27      1  520  3.74         4
28      1  780  3.22         2
29      0  520  3.29         1
..    ...  ...   ...       ...
70      0  640  4.00         3
71      0  300  2.92         4
72      0  480  3.39         4
73      0  580  4.00         2
74      1  720  3.45         4
75      1  720  4.00         3
76      0  560  3.36         3
77      1  800  4.00         3
78      0  540  3.12         1
79      1  620  4.00         1
80      0  700  2.90         4
81      0  620  3.07         2
82      0  500  2.71         2
83      0  380  2.91         4
84      1  500  3.60         3
85      0  520  2.98         2
86      0  600  3.32         2
87      0  600  3.48         2
88      1  700  3.28         1
89      1  660  4.00         2
90      1  700  3.83         2
91      1  720  3.64         1
92      1  800  3.90         2
93      0  580  2.93         2
94      1  660  3.44         2
95      0  660  3.33         2
96      0  640  3.52         4
97      0  480  3.57         2
98      0  700  2.88         2
99      0  400  3.31         3

[100 rows x 4 columns]

## Step 2: Do some summary analytics

** Do a describe() on the data **

```python
print(df.describe())
```

** Get the Standard deviation by Column
```python
df.std()
```

In [ ]:
# TODO: Do a Describe on the data

In [ ]:
# TODO: Get Standard Deviation by column

### Crossstab

We can do a frequency table crosstab like this:

```python
print(pd.crosstab(admissions['admit'], admissions['prestige'], rownames=['admit']))
```

In [ ]:
#TODO: Do a Frequency Table Crosstab

In [ ]:
### Histogram

You can do a histogram simply by doing dataframe.hist()

In [ ]:
#TODO: Perform a histogram

In [10]:
dummy_ranks = pd.get_dummies(admissions['prestige'], prefix='prestige')
print(dummy_ranks.head())

   prestige_1  prestige_2  prestige_3  prestige_4
0           0           0           1           0
1           0           0           1           0
2           1           0           0           0
3           0           0           0           1
4           0           0           0           1

In [14]:
# create a clean data frame for the regression
cols_to_keep = ['admit', 'gre', 'gpa']
data = admissions[cols_to_keep].join(dummy_ranks.loc[:, 'prestige_2':])
data

    admit  gre   gpa  prestige_2  prestige_3  prestige_4
0       0  380  3.61           0           1           0
1       1  660  3.67           0           1           0
2       1  800  4.00           0           0           0
3       0  640  3.19           0           0           1
4       0  520  2.93           0           0           1
5       1  760  3.00           1           0           0
6       0  560  2.98           0           0           0
7       0  400  3.08           1           0           0
8       0  540  3.39           0           1           0
9       1  700  3.92           1           0           0
10      1  800  4.00           0           0           1
11      0  440  3.22           0           0           0
12      1  760  4.00           0           0           0
13      1  700  3.08           1           0           0
14      1  700  4.00           0           0           0
15      0  480  3.44           0           1           0
16      1  780  3.87           0           0           1
17      0  360  2.56           0           1           0
18      1  800  3.75           1           0           0
19      0  540  3.81           0           0           0
20      0  500  3.17           0           1           0
21      1  660  3.63           1           0           0
22      0  600  2.82           0           0           1
23      0  680  3.19           0           0           1
24      1  760  3.35           1           0           0
25      1  800  3.66           0           0           0
26      1  620  3.61           0           0           0
27      1  520  3.74           0           0           1
28      1  780  3.22           1           0           0
29      0  520  3.29           0           0           0
..    ...  ...   ...         ...         ...         ...
70      0  640  4.00           0           1           0
71      0  300  2.92           0           0           1
72      0  480  3.39           0           0           1
73      0  580  4.00           1           0           0
74      1  720  3.45           0           0           1
75      1  720  4.00           0           1           0
76      0  560  3.36           0           1           0
77      1  800  4.00           0           1           0
78      0  540  3.12           0           0           0
79      1  620  4.00           0           0           0
80      0  700  2.90           0           0           1
81      0  620  3.07           1           0           0
82      0  500  2.71           1           0           0
83      0  380  2.91           0           0           1
84      1  500  3.60           0           1           0
85      0  520  2.98           1           0           0
86      0  600  3.32           1           0           0
87      0  600  3.48           1           0           0
88      1  700  3.28           0           0           0
89      1  660  4.00           1           0           0
90      1  700  3.83           1           0           0
91      1  720  3.64           0           0           0
92      1  800  3.90           1           0           0
93      0  580  2.93           1           0           0
94      1  660  3.44           1           0           0
95      0  660  3.33           1           0           0
96      0  640  3.52           0           0           1
97      0  480  3.57           1           0           0
98      0  700  2.88           1           0           0
99      0  400  3.31           0           1           0

[100 rows x 6 columns]


## Step 4: Run Logistic Regression in StatsModel

Let's run our logistic regression.  To do this we need to run call the Logit Class in statsmodel

In [15]:
data['intercept'] = 1.0

In [17]:
data

    admit  gre   gpa  prestige_2  prestige_3  prestige_4  intercept
0       0  380  3.61           0           1           0        1.0
1       1  660  3.67           0           1           0        1.0
2       1  800  4.00           0           0           0        1.0
3       0  640  3.19           0           0           1        1.0
4       0  520  2.93           0           0           1        1.0
5       1  760  3.00           1           0           0        1.0
6       0  560  2.98           0           0           0        1.0
7       0  400  3.08           1           0           0        1.0
8       0  540  3.39           0           1           0        1.0
9       1  700  3.92           1           0           0        1.0
10      1  800  4.00           0           0           1        1.0
11      0  440  3.22           0           0           0        1.0
12      1  760  4.00           0           0           0        1.0
13      1  700  3.08           1           0           0        1.0
14      1  700  4.00           0           0           0        1.0
15      0  480  3.44           0           1           0        1.0
16      1  780  3.87           0           0           1        1.0
17      0  360  2.56           0           1           0        1.0
18      1  800  3.75           1           0           0        1.0
19      0  540  3.81           0           0           0        1.0
20      0  500  3.17           0           1           0        1.0
21      1  660  3.63           1           0           0        1.0
22      0  600  2.82           0           0           1        1.0
23      0  680  3.19           0           0           1        1.0
24      1  760  3.35           1           0           0        1.0
25      1  800  3.66           0           0           0        1.0
26      1  620  3.61           0           0           0        1.0
27      1  520  3.74           0           0           1        1.0
28      1  780  3.22           1           0           0        1.0
29      0  520  3.29           0           0           0        1.0
..    ...  ...   ...         ...         ...         ...        ...
70      0  640  4.00           0           1           0        1.0
71      0  300  2.92           0           0           1        1.0
72      0  480  3.39           0           0           1        1.0
73      0  580  4.00           1           0           0        1.0
74      1  720  3.45           0           0           1        1.0
75      1  720  4.00           0           1           0        1.0
76      0  560  3.36           0           1           0        1.0
77      1  800  4.00           0           1           0        1.0
78      0  540  3.12           0           0           0        1.0
79      1  620  4.00           0           0           0        1.0
80      0  700  2.90           0           0           1        1.0
81      0  620  3.07           1           0           0        1.0
82      0  500  2.71           1           0           0        1.0
83      0  380  2.91           0           0           1        1.0
84      1  500  3.60           0           1           0        1.0
85      0  520  2.98           1           0           0        1.0
86      0  600  3.32           1           0           0        1.0
87      0  600  3.48           1           0           0        1.0
88      1  700  3.28           0           0           0        1.0
89      1  660  4.00           1           0           0        1.0
90      1  700  3.83           1           0           0        1.0
91      1  720  3.64           0           0           0        1.0
92      1  800  3.90           1           0           0        1.0
93      0  580  2.93           1           0           0        1.0
94      1  660  3.44           1           0           0        1.0
95      0  660  3.33           1           0           0        1.0
96      0  640  3.52           0           0           1        1.0
97      0  480  3.57           1           0           0        1.0
98      0  700  2.88           1           0           0        1.0
99      0  400  3.31           0           1           0        1.0

[100 rows x 7 columns]

In [18]:
result = sm.Logit(admissions['admit'], data[data.columns[1:]]).fit()
result

Optimization terminated successfully.
         Current function value: 0.408573
         Iterations 7

In [19]:
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:                  admit   No. Observations:                  100
Model:                          Logit   Df Residuals:                       94
Method:                           MLE   Df Model:                            5
Date:                Tue, 20 Feb 2018   Pseudo R-squ.:                  0.4021
Time:                        23:42:58   Log-Likelihood:                -40.857
converged:                       True   LL-Null:                       -68.331
                                        LLR p-value:                 1.338e-10
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
gre            0.0141      0.003      4.104      0.000       0.007       0.021
gpa            1.8221      0.888      2.052      0.040       0.082       3.563
prestige_2     0.5516      0.808      0.683      0.495      -1.032       2.135
prestige_3     0.3926      0.854      0.460      0.646      -1.281       2.066
prestige_4    -1.0491      0.965     -1.087      0.277      -2.940       0.842
intercept    -15.2991      3.502     -4.369      0.000     -22.162      -8.436
==============================================================================
"""

In [21]:
result.conf_int()

                    0         1
gre          0.007364  0.020828
gpa          0.081661  3.562552
prestige_2  -1.032085  2.135275
prestige_3  -1.280697  2.065850
prestige_4  -2.940259  0.842005
intercept  -22.162085 -8.436214